### ISSUE TITLE
bqZUM_Scan_Shield.TXT file format error

### ISSUE THREAD

**Issue by AndrewJamesTurner** [bq/zum#11]
I just went to get one of the Zum Scan boards made up and it appears there is some sort of error. The drill holes do not align with the holes on the board. When you view them using gerbv the drill holes are bunched up in the lower left corner. See image
![screenshot from 2015-03-18 10 44 18](https://cloud.githubusercontent.com/assets/6958824/6707132/dd2c1bee-cd5b-11e4-8c53-e6ab6d5e057c.png)

**Comment by deusyss** [comment]
Hi,

i have same problem when i try to convert the gerber/drill file for OSH Park (https://oshpark.com/shared_projects/DvU87rGe).

But i realized it was just parameters to open the files which was the problem. I think you have a parameter problem too.
