### ISSUE TITLE
Gerber Files should NOT contain measurement information... 

### ISSUE THREAD

**Issue by spaelectronics** [bq/zum#19]
The Gerber Files for the "Zum Scan Shield" should NOT contain measurement information... This makes the board cost more to purchase from services like oshpark.com

OshPark charges for a PCB Size that is larger than the actual board. You should remove this measurement text from the gerber files.

**Comment by alvaroferran** [comment]
Thanks for the comment, the file has been revised and updated.

**Comment by spaelectronics** [comment]
Could you please also update the ZumScanForOshPark.zip file?

**Comment by alvaroferran** [comment]
Done! 26dd5a0d407dee24d29ebb8183cdb2730e75f127
