### ISSUE TITLE
Gerber & drill format

### ISSUE THREAD

**Issue by deusyss** [bq/zum#8]
Hi,

I saw you design electronic card with Altium, a very good software but not free. Drill file are not recognize by several PCB manufacturer which ask to me (as Gerber viewer in KICAD) Excellon files (NC Drills format file, http://techdocs.altium.com/display/ADOH/NC+Drill+Output+Options).

Could you generate these file for the community which use KICAD please? 

Thank you

**Comment by Obijuan** [comment]
Thanks deusyss!

We are in the process of migrating everything to open formats. All the 3D designs (3D printers, scanner, CNC machines and printbots) are being migrated to Freecad. The electronics will be migrated to Kicad. 

The first step is to publish all the source files in github with open licenses. Then, with the help of the community, everything will be migrated.  Any pull request in this direction will be welcome

**Comment by deusyss** [comment]
Hi,
Good news (and good jobs). I'm going to try to convert STL into freecad object format thiw week-end. Hope post soon pull request in this way.
