### ISSUE TITLE
BOM does not give specifications for electronic parts

### ISSUE THREAD

**Issue by jbernardis** [bq/zum#9]
The BOM provides the footprint for the components, but not the specifications.  I was able through persistent searching to determine that R1 and R2 are 10k 1/4 watt, c1 and c2 are 100 microfarads 50v, and Q1 through Q4 are BS170 transistor, but I cannot anywhere find the specifications for the PTC fuses.  

I imagine that this will be available once the kicad sources are available, but I was hoping to find out sooner.

**Comment by DaveyRance** [comment]
I Also have the same issue with the PTC fuses.  Would it please be possible to give the spec's for them.

I have a parts list / project on mouser for the parts but i had to guess as what would be needed for the PTC

**Comment by Obijuan** [comment]
The Fuse reference is MF-R185 (zumscan board)

**Comment by DaveyRance** [comment]
Great thanks for that.  

I have updated the project on Mouser that should have a full BOM now.

http://www.mouser.com/ProjectManager/ProjectDetail.aspx?AccessID=6952239cf8

If anyone finds any errors let me know and i will update or if they find cheaper parts there for the same things like the headers let me know and i will update.
